//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFA_DEMO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Items_Reviews = new HashSet<Items_Reviews>();
            this.User_Inventory = new HashSet<User_Inventory>();
            this.Properties = new HashSet<Property>();
            InitAvatarManagement();
        }
    
        public int IdObject { get; set; }
        [Display(Name = "Nom")]
        [Required]
        public string Name { get; set; }
        [Display(Name = "Quantité en stock")]
        [Required]
        public int StockQuantity { get; set; }
        [Display(Name = "Prix")]
        [Required]
        public double Price { get; set; }
        [Display(Name = "Image")]
        [Required]
        public string PictureGUID { get; set; }
        [Display(Name = "Type")]
        [Required]
        public int? IdType { get; set; }
    
        public virtual Items_Type Items_Type { get; set; }

        [Display(Name = "Avatar")]
        public string AvatarImageData { get; set; }
        private ImageGUIDReference AvatarReference { get; set; }

        public void InitAvatarManagement()
        {
            AvatarReference = new ImageGUIDReference(@"/Images/", @"no_image.png");
            AvatarReference.MaxSize = 512;
            AvatarReference.HasThumbnail = false;
        }
        public String GetAvatarURL()
        {
            return AvatarReference.GetURL(PictureGUID, false);
        }
        public void SaveAvatar()
        {
            PictureGUID = AvatarReference.SaveImage(AvatarImageData, PictureGUID);
        }
        public void RemoveAvatar()
        {
            AvatarReference.Remove(PictureGUID);
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items_Reviews> Items_Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Inventory> User_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
    }
}
