//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chevaleresk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChevalereskDBEntities2 : DbContext
    {
        public ChevalereskDBEntities2()
            : base("name=ChevalereskDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Items_Reviews> Items_Reviews { get; set; }
        public virtual DbSet<Items_Type> Items_Type { get; set; }
        public virtual DbSet<Player_Inventory> Player_Inventory { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<Properties> Properties { get; set; }
    }
}
