//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chevaleresk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player_Inventory
    {
        public int IdPlayer { get; set; }
        public int IdObject { get; set; }
        public int Quantity { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Players Players { get; set; }
    }
}
